[package]
name = "rpomo"
version = "0.1.0"
authors = ["Michael Schumacher <schumacher.m@me.com>"]

[dependencies]
clap = "2.29.2"
serde = "1.0.27"
serde_json = "1.0.9"
serde_derive = "1.0.27"
chrono = "0.4.0"

[profile.release]
codegen-units = 32
debug = false
